#!/usr/bin/env bash
set -euo pipefail

# Toggle local crate overrides by writing/removing .cargo/config.toml.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$ROOT/.cargo"
CONFIG_PATH="$CONFIG_DIR/config.toml"

if [[ "${1-}" == "disable" ]]; then
  rm -f "$CONFIG_PATH"
  echo "Removed $CONFIG_PATH (registry resolutions restored)."
  exit 0
fi

mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_PATH" <<'EOF'
# Generated by scripts/dev-local.sh
[patch.crates-io]
cortenforge-sim-core = { path = "../cortenforge-sim-core" }
cortenforge-vision-core = { path = "../cortenforge-vision-core" }
cortenforge-vision-runtime = { path = "../cortenforge-vision-runtime" }
cortenforge-data-contracts = { path = "../cortenforge-data-contracts" }
cortenforge-inference = { path = "../cortenforge-inference" }
cortenforge-capture-utils = { path = "../cortenforge-capture-utils" }
cortenforge-models = { path = "../cortenforge-models" }
cortenforge-burn-dataset = { path = "../cortenforge-burn-dataset" }
EOF

echo "Wrote $CONFIG_PATH with local patch overrides. Edit paths if your clones live elsewhere."
